version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: example
      TZ: Asia/Tokyo
    command:
      [
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
        --default-authentication-plugin=mysql_native_password,
      ]
    ports:
      - 3306:3306

  dynamodb:
    image: amazon/dynamodb-local:1.21.0
    user: root
    container_name: dynamodb_server
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data sharedDb
    volumes:
      - ./data/dynamodb:/data
    ports:
      - 8000:8000
    
  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin:4.5.1
    environment:
      - DYNAMO_ENDPOINT=dynamodb:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb