name: Rust CI

on:
  push:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mysql-version: [ '8.0' ]
        mysql-dbname: [ 'example' ]
        mysql-root-user: [ 'root' ]
        mysql-root-password: [ 'password' ]

    services:
      db:
        image: mysql:${{ matrix.mysql-version }}
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: ${{ matrix.mysql-dbname }}
          MYSQL_ROOT_USER: ${{ matrix.mysql-root-user }}
          MYSQL_ROOT_PASSWORD: ${{ matrix.mysql-root-password }}
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000
        env:
          AWS_REGION: ap-northeast-1
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy

    name: Rust project
    steps:
      - uses: actions/checkout@v3
      - run: aws dynamodb create-table --cli-input-json file://users-table.json --endpoint-url http://localhost:8000
      - run: aws dynamodb describe-table --table-name users-table --endpoint-url http://localhost:8000

      - name: Run SQL on Service
        run: |
          SQL_FILES=$(find . -name "*.sql" | sort)
          for FILE in $SQL_FILES; do
            echo "Running SQL file: $FILE"
            mysql -h 127.0.0.1 --port 3306 -u ${{ matrix.mysql-root-user }} -p${{ matrix.mysql-root-password }} -D ${{ matrix.mysql-dbname }} < $FILE
          done

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          RUST_LOG: debug
          PORT: 8080
          HOST: 127.0.0.1
          MYSQL_DSN: mysql://root:password@localhost:3306/example
          DYNAMODB_URI: http://localhost:8000




