name: Rust CI

on:
  push:

env:
  RUST_LOG: debug
  HOST: 127.0.0.1
  PORT: 8080
  MYSQL_DSN: mysql://root:password@localhost:33063/example

jobs:
  build_and_test:
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 33063:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: example
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          PORT: ${{ env.PORT }}
          HOST: ${{ env.HOST }}
          MYSQL_DSN: ${{ env.MYSQL_DSN }}





